averageRating fix
kir-dev/konzisite-api pull request #119
Opened 2023-02-06 19:04 UTC by DannySS123

2023-02-06 19:44 UTC, Tschonti requested changes
Good job, just one small thing

2023-02-06 19:44 UTC, Tschonti commented on src/consultations/consultations.service.ts
> +        averageRating: averageRatings[index],
Don't send the whole user object, just the public fields: id and fullname (this was done with projection previously, but that's not possible anymore, so just do it manually here)

2023-02-06 20:47 UTC, Tschonti approved these changes

2023-02-07 14:25 UTC, kisbogdan-kolos approved these changes

2023-02-07 14:43 UTC, merged