Feature/consultation page update
kir-dev/konzisite-api pull request #127
Opened 2023-02-20 19:42 UTC by DannySS123

2023-02-20 21:36 UTC, kisbogdan-kolos requested changes
Invalid value of `major` parameter results in a 500 error. I think this should be a 400, `Nincs ilyen szak!`.

2023-02-21 11:23 UTC, DannySS123 commented
For some reason when the major is bad (probobly more like an enum is bad) the error doesn't have a code. 😞

2023-02-21 13:12 UTC, kisbogdan-kolos approved these changes

2023-02-21 19:47 UTC, Tschonti approved these changes

2023-02-21 19:55 UTC, merged