Eng to hun error messages
kir-dev/konzisite-api pull request #80
Opened 2023-01-16 18:04 UTC by DannySS123

- Updated some error messages to Hungarian
- 401 and 403 to be handled from the frontend
- Disabled some eslint warnings

closes #68

2023-01-16 19:26 UTC, Tschonti requested changes

2023-01-16 19:26 UTC, Tschonti commented on src/auth/casl-ability.factory.ts
>      const { can, cannot, build } = new AbilityBuilder<AppAbility>(
`cannot` is not used at all in this function, so this warning was valid, we can remove `cannot`

2023-01-16 21:00 UTC, Tschonti approved these changes

2023-01-20 16:40 UTC, kisbogdan-kolos approved these changes

2023-01-20 19:31 UTC, merged