Consultation join permission
kir-dev/konzisite-api pull request #90
Opened 2023-01-24 12:03 UTC by DannySS123

- Closes #84

2023-01-24 17:13 UTC, Tschonti requested changes
noice
One more thing: add the JoinConsultations RequiredPermission to the PATCH `/:id/rate` endpoint as well

2023-01-24 17:13 UTC, Tschonti commented on src/consultations/consultations.controller.ts
>          'A konzultáció nem található!',
Not related to this issue, but `consultationService.findOne` already handles the Not Found case, no need for the try-catch here,

2023-01-24 17:13 UTC, Tschonti commented on src/auth/casl-ability.factory.ts
> +      cannot(Permissions.JoinConsultation, 'Consultation')
`cannot` is not actually needed here. CASL won't let you access the resource unless it was explicitly specified with a `can`. The only use of `cannot` is to override a previous `can`. This `cannot` even prevents admins from joining their own consultations, which isn't really a problem, but still kinda unexpected behaviour

2023-01-24 19:41 UTC, Tschonti approved these changes

2023-01-25 11:30 UTC, kisbogdan-kolos approved these changes

2023-01-25 12:30 UTC, merged